# Generated by Django 4.2.1 on 2023-06-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('MX', 'iPhone Pro Max'), ('PR', 'iPhone Pro'), ('IP', 'iPhone')], max_length=2),
        ),
    ]
